### ISSUE TITLE
giúp mình mới mình dung gf63 thin 9rcx giống hệt bạn nhưng boot vào cài mac 10.15 không được

### ISSUE THREAD

**Issue by zaidenhn** [quan3c10/Hackintosh-MSI-GF63-Thin-9RC-273VN#1]
giúp mình mới mình dung gf63 thin 9rcx giống hệt bạn nhưng boot vào cài mac 10.15 không được

**Comment by quan3c10** [comment]
Bạn đang cài hay cài xong rồi?

**Comment by zaidenhn** [comment]
boot vào bộ cài bạn. lỗi ko boot đc 
bạn có zalo hay gì ko mình gửi ảnh bạn xem.

**Comment by quan3c10** [comment]
Nếu cài thì bạn dùng EFI này nhé https://tinyurl.com/vpecysf
Sau khi cài xong thì thay bẳng EFI của mình, EFI của mình có kext devices sẽ ko nhận khi chưa cài đặt nên ko boot đc.

**Comment by quan3c10** [comment]
Add face mình nếu vẫn ko đc nhé https://www.facebook.com/quan.hong.3192/
Nếu được rồi thì Close issue giúp mình nhé
