### ISSUE TITLE
GioScreenLockState Isue

### ISSUE THREAD

**Issue by radityabh** [quan3c10/Hackintosh-MSI-GF63-Thin-9RC-273VN#2]
Hallo @quan3c10 , i have laptop similar at yours MSI GF63 Thin 9rcx Laptop i5-9300H GeForce GTX 1050ti. I use your efi folder, but i stuck in ACM: deleteCredintialSet. after IOConsoleUsers:gIoScreenlockState 3hs. are you have solution for my problems? thanks you

**Comment by quan3c10** [comment]
My EFI folder isn't usage for installation, please use this efi instead then you could use mine for post configure. https://tinyurl.com/vpecysf

**Comment by radityabh** [comment]
> My EFI folder isn't usage for installation, please use this efi instead then you could use mine for post configure. https://tinyurl.com/vpecysf

thank you very much for your answer. but i have success on installation. i use your EFi Folder because my graphics VRAM just 7mb. any solution for this?

**Comment by quan3c10** [comment]
> > My EFI folder isn't usage for installation, please use this efi instead then you could use mine for post configure. https://tinyurl.com/vpecysf
> 
> thank you very much for your answer. but i have success on installation. i use your EFi Folder because my graphics VRAM just 7mb. any solution for this?

If the VRAM only 7mb it related to the incorrect framebuffer please use the hackintool to repatch

**Comment by radityabh** [comment]
> > > My EFI folder isn't usage for installation, please use this efi instead then you could use mine for post configure. https://tinyurl.com/vpecysf
> > 
> > 
> > thank you very much for your answer. but i have success on installation. i use your EFi Folder because my graphics VRAM just 7mb. any solution for this?
> 
> If the VRAM only 7mb it related to the incorrect framebuffer please use the hackintool to repatch

what i must choose in platform-id ? because i not get red line in connector tab

**Comment by quan3c10** [comment]
Did you try all the coffeelake id?

**Comment by radityabh** [comment]
> Did you try all the coffeelake id?

I fresh install with catalina 10.15.3, now my vram work. but my sound not work, have solition? thanks

**Comment by quan3c10** [comment]
The sound is related to your sound card type, it patched by AppleALC. Please following the AppleALC guide to pick the correct layout id

**Comment by radityabh** [comment]
> The sound is related to your sound card type, it patched by AppleALC. Please following the AppleALC guide to pick the correct layout id

ok, now i try one by one the layout. whats your gf63 sound card type and layout?

**Comment by quan3c10** [comment]
Mine type is ALC 269 with layout id is 30

**Comment by radityabh** [comment]
ok, thank you man, now my vram and audio work. but my hdmi port not work, have any solution?

**Comment by quan3c10** [comment]
did you try my patch? If it still the issue, you do the wrong patching

**Comment by radityabh** [comment]
> did you try my patch? If it still the issue, you do the wrong patching

i dont use your patch, because when i use your patch my vram just 1 mb

**Comment by radityabh** [comment]
Done, my hdmi work with modify patch. thankyou very much @quan3c10

**Comment by quan3c10** [comment]
You are welcome! 👍
