### ISSUE TITLE
if it is possible to install

### ISSUE THREAD

**Issue by dobbroe** [quan3c10/Hackintosh-MSI-GF63-Thin-9RC-273VN#3]
Good afternoon! I am not good at this topic, but could you tell me if it is possible to install your MacOS assembly on my laptop MSI gf63 9RC 16r3, i5 9300H? Maybe we could contact by gmail or by the method of communication convenient for you?

**Comment by quan3c10** [comment]
Of course, please use the EFI in link below to installation and use my configure for post installation. Don't forget do some research first, and following the issue #2 . Good luck!
https://tinyurl.com/vpecysf
