### ISSUE TITLE
Black screen when installing

### ISSUE THREAD

**Issue by looklukelike** [quan3c10/Hackintosh-MSI-GF63-Thin-9RC-273VN#4]
Tried using your EFI folder but have black screen when booting from the usb installer and clover. Which arguments did you booth up with. And which version of bootloader did you go with?

**Comment by quan3c10** [comment]
Related to #3, this EFI use for post install not the installation.

**Comment by looklukelike** [comment]
Ok I have copied the files in the EFI folder from https://tinyurl.com/vpecysf. I still get a black screen, tried verbose and disabling nvidia drivers again. Amything more I need to do?

**Comment by quan3c10** [comment]
> Ok I have copied the files in the EFI folder from https://tinyurl.com/vpecysf. I still get a black screen, tried verbose and disabling nvidia drivers again. Amything more I need to do?

Which step you got the black screen? Also make sure you researched about the installation progress, we also need to config your BIOS too.

**Comment by looklukelike** [comment]
Just after selecting the osx installer from clover. Configured the bios using all the suggested settings. 

- disable fast boot
- enable vx t
- UEFI mode
- disable secure boot

**Comment by quan3c10** [comment]
verbose log will help. Which type of your laptop?

**Comment by looklukelike** [comment]
laptop is	GF63 Thin 10SCXR. Would be great what the actual verbose output is but nothing comes up on screen.

I tried using the Clover/EFI folder of this release (for MSI GS65) and that actually works but then installer hangs at

Random Seed 
+++++++++++++

The other release I used is this one: 
https://github.com/tmtd2/MSI-GS65-clover and the guide is https://www.tonymacx86.com/threads/guide-msi-gs65-stealth-thin-8rf-mojave.278198/

**Comment by quan3c10** [comment]
It may related to newest CPU gen 10th. You may need to find the correct SMBIOS for that one.
